package Telas;

import Controles.UsuarioControle;
import Entidades.Usuario;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Calel Freitas 
 */
public class GerenciarUsuario extends javax.swing.JFrame {

    private UsuarioControle controle = new UsuarioControle();
    
    public GerenciarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastrarUsuario = new javax.swing.JButton();
        EditarUsuario = new javax.swing.JButton();
        InativarUsuario = new javax.swing.JButton();
        MostrarUsuario = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GerenciarUsuario");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciar Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 17))); // NOI18N

        CadastrarUsuario.setText("Cadastrar usuário");
        CadastrarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });

        EditarUsuario.setText("Editar usuário");
        EditarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarUsuarioActionPerformed(evt);
            }
        });

        InativarUsuario.setText("inativar usuário");
        InativarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        InativarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InativarUsuarioActionPerformed(evt);
            }
        });

        MostrarUsuario.setText("Mostrar usuário");
        MostrarUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MostrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MostrarUsuario)
                    .addComponent(InativarUsuario)
                    .addComponent(EditarUsuario)
                    .addComponent(CadastrarUsuario))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(CadastrarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InativarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarUsuario)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        Sair.setBackground(new java.awt.Color(204, 0, 51));
        Sair.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        Sair.setText("X");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        this.dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
        String nome = JOptionPane.showInputDialog("Nome:");
        String login = JOptionPane.showInputDialog("Login:");
        String senha = JOptionPane.showInputDialog("Senha:");
        
        if (nome != null && login != null && senha != null) {
           Usuario usuario = new Usuario(UsuarioControle.ultimoIdGlobal++, nome, login, senha, true);
           boolean sucesso = controle.cadastrarUsuario(usuario);
           JOptionPane.showMessageDialog(null, sucesso ? "Usuário cadastrado!" : "Erro: login já existe.");
                }
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    private void InativarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InativarUsuarioActionPerformed
        String login = JOptionPane.showInputDialog("Login do usuário a inativar:");
        if (login != null) {
           boolean sucesso = controle.inativarUsuario(login);
           JOptionPane.showMessageDialog(null, sucesso ? "Usuário inativado com sucesso!" : "Erro: usuário não encontrado.");
        }
    }//GEN-LAST:event_InativarUsuarioActionPerformed

    private void EditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarUsuarioActionPerformed
        String login = JOptionPane.showInputDialog("Login do usuário a editar:");
        String novoNome = JOptionPane.showInputDialog("Novo nome:");
        String novaSenha = JOptionPane.showInputDialog("Nova senha:");
        String novoTipo = JOptionPane.showInputDialog("Tipo (Administrador/Comum):");

        if (login != null && novoNome != null && novaSenha != null && novoTipo != null) {
        boolean sucesso = controle.editarUsuario(login, novoNome, novaSenha, novoTipo);
        JOptionPane.showMessageDialog(null, sucesso ? "Usuário editado com sucesso!" : "Erro ao editar.");
        }
    }//GEN-LAST:event_EditarUsuarioActionPerformed

    private void MostrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarUsuarioActionPerformed
        List<Usuario> lista = controle.listarUsuarios();
        StringBuilder sb = new StringBuilder("Usuários cadastrados:\n");
        for (Usuario u : lista) {
          sb.append("- ").append(u.getNome())
            .append(" | Login: ").append(u.getLogin())
            .append(" | Ativo: ").append(u.isAtivo() ? "Sim" : "Não")
            .append("\n");
        }
        JOptionPane.showMessageDialog(null, sb.toString());
    }//GEN-LAST:event_MostrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarUsuario;
    private javax.swing.JButton EditarUsuario;
    private javax.swing.JButton InativarUsuario;
    private javax.swing.JButton MostrarUsuario;
    private javax.swing.JButton Sair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
